### ISSUE TITLE
Various isolates tests assume synchronous errors, fail in 1.14 BE

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#13] opened 2015-11-24 18:50 UTC
Isolate spawning behaviour has changed to be more spec-compliant and faster in 1.14. There are various tests which assume that if there's an exception it can be caught by wrapping the spawn call in a try/catch block, or that the test can just be suppressed in a status file if it doesn't catch the isolate spawning error at all. This no longer works, it has to handle the error on the returned future. As a result the tests spuriously pass.

Affected tests are

co19/LibTest/isolate/ReceivePort/close_A02_t01
co19/LibTest/isolate/ReceivePort/close_A01_t01
co19/LibTest/isolate/ReceivePort/asBroadcastStream_A01_t02
co19/LibTest/isolate/ReceivePort/asBroadcastStream_A03_t02
co19/LibTest/isolate/ReceivePort/asBroadcastStream_A03_t01
co19/LibTest/isolate/ReceivePort/asBroadcastStream_A03_t03
co19/LibTest/isolate/RawReceivePort/close_A01_t01

@a-siva @terrylucas

**Comment by alsemenov** [comment] 2015-11-27 04:44
I agree that close_A* tests should be changed to become asynchronous.

Regarding asBroadcastStream_A*, please, clarify the problem.

The documentation for Isolate.spawn() reads (https://api.dartlang.org/1.13.0/dart-isolate/Isolate/spawn.html ):
>Returns a future that will complete with an Isolate instance if the spawning succeeded. 
>It will complete with an error otherwise.

The documentation for Future ( https://api.dartlang.org/1.13.0/dart-async/Future-class.html ):
>A Future can complete in two ways: with a value ("the future succeeds") or with an error ("the future >fails"). Users can install callbacks for each case. The result of registering a pair of callbacks is a new >Future (the "successor") which in turn is completed with the result of invoking the corresponding >callback. The successor is completed with an error if the invoked callback throws. 
>...
>If a future does not have a successor when it completes with an error, it forwards the error message >to the global error-handler. This behavior makes sure that no error is silently dropped. 

As far as I understand Isolate.spawn() is not supported on Dartium.
Does it throw an exception or some other kind of error occurs?

The tests  asBroadcastStream_A* call Isolate.spawn() without any error callbacks or try-catch wrappers. So if spawning fails, global error handler should catch this and fail the test. Such test design conforms with the current specification and is simple and robust. If the try-catch wrapper or global error handler is not able to catch the error, it is probably another bug.

**Comment by alsemenov** [comment] 2015-11-30 11:24
https://github.com/dart-lang/co19/commit/8879dbe288de7009e011b69a62759c104d270042 fix close_A* tests

**Comment by alan-knight** [comment] 2015-11-30 20:51
On Dartium Isolate.spawn used to throw synchronously. Now it will more correctly complete the returned future with an error. Picking one of these tests, LibTest/isolate/ReceivePort/asBroadcastStream_A03_t02 

```
main() {
  asyncStart();
  runZoned(f, onError: (_) {
    asyncEnd();
  });
}
```

This test passes on Dartium, even though the broadcast stream is never successfully created. The onError: parameter to the zone catches the error spawning, ignores it, and calls asyncEnd(). The test completes without any failing asserts, even though there's a stack trace printed to the output, so it passes.

**Comment by alsemenov** [comment] 2015-12-07 11:14
I believe the problem is fixed now. Please, verify.

**Closed by alsemenov** 2015-12-07 11:14 UTC
