### ISSUE TITLE
FileStat.notFound tests needs to allow epoch timestamps

### ISSUE THREAD

**Issue by sortie** [dart-lang/co19#573] opened 2020-03-11 13:29 UTC
The `io/FileStat/stat_A02_t01` and `io/FileStat/statSync_A02_t01` tests need to be updated to allow the notFound object to contain epoch timestamps rather than null timestamps. The intended behavior changed in the https://github.com/dart-lang/sdk/issues/40706 breaking change, which landed in https://dart-review.googlesource.com/c/sdk/+/136585.

Example failures: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8886218047260541696/+/steps/test_results/0/logs/new_test_failures__logs_/0

**Comment by eernstg** [comment] 2020-03-11 13:56
Thanks for noting this issue! However, I believe it would be a duplicate of #543.

**Comment by eernstg** [comment] 2020-03-11 14:01
Closing&mdash;having added a link to this issue in #543, such that the additional url here may be known.

**Closed by eernstg** 2020-03-11 14:01 UTC

**Comment by sortie** [comment] 2020-03-11 14:32
Thanks Erik. I wasn't aware of the other issue, didn't expect you to help out, thanks :)
