### ISSUE TITLE
Incorrect comparison in test

### ISSUE THREAD

**Issue by a-siva** [dart-lang/co19#489] opened 2019-10-04 01:52 UTC
tests/co19_2/src/LanguageFeatures/Extension-methods/call_member_t01.dart seems to incorrectly compare a List with a _GeneratorIterable<int> type.

```
extension Tricky on int {
  Iterable<int> call(int to) =>
    Iterable<int>.generate(to - this + 1, (i) => i + this);
}

main() {
  Expect.listEquals([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 1(10));
  Expect.listEquals([2, 3, 4, 5], 2(5));
}
```

Should probably be written as
```
  Expect.listEquals([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 1(10).toList());
  Expect.listEquals([2, 3, 4, 5], 2(5).toList());
```

**Comment by sgrekhov** [comment] 2019-10-04 03:31
Duplicate of #483

**Closed by sgrekhov** 2019-10-04 03:31 UTC
