### ISSUE TITLE
co19/LanguageFeatures/Patterns/variable_declaration_A06_t02

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#1839] opened 2023-02-07 21:57 UTC
The specification only allows pattern variables declarations for locals.

https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#pattern-variable-declaration

```
FAILED: dart2analyzer-none release_arm64 co19/LanguageFeatures/Patterns/variable_declaration_A06_t02
Expected: Pass
Actual: MissingCompileTimeError

--- Command "dart2analyzer" (took 06.000339s):
DART_CONFIGURATION=ReleaseARM64 sdk/bin/dart --packages=.dart_tool/package_config.json pkg/analyzer_cli/bin/analyzer.dart --use-analysis-driver-memory-byte-store --dart-sdk=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk -Dtest_runner.configuration=custom-configuration-1 --enable-experiment=patterns,records --ignore-unrecognized-flags --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.dart_tool/package_config.json --format=json /Users/scheglov/Source/Dart/sdk.git/sdk/tests/co19/src/LanguageFeatures/Patterns/variable_declaration_A06_t02.dart

static error failures:
- Unexpected error at line 31, column 3, length 42: COMPILE_TIME_ERROR.CONCRETE_CLASS_WITH_ABSTRACT_MEMBER

--- Re-run this test:
python3 tools/test.py -m release -c dart2analyzer -a arm64 co19/LanguageFeatures/Patterns/variable_declaration_A06_t02
```

**Comment by sgrekhov** [comment] 2023-02-08 09:17
@scheglov this test checks the statement that pattern variables declarations are allowed for local variables only. And the test expects a compile-time error if patterns are used for declaring static variables. So, the test should be ok, but we have unexpected failure on metadata. 

https://github.com/dart-lang/co19/blob/3327cf93e2dc31bfa6fe8e97085125f4da85255e/LanguageFeatures/Patterns/variable_declaration_A06_t02.dart#L30-L35

```
- Unexpected error at line 31, column 3, length 42: COMPILE_TIME_ERROR.CONCRETE_CLASS_WITH_ABSTRACT_MEMBER
```
Do we really should have such error here? I think, first, this error it is not relevant. Second, there shouldn't be error here at all.

@eernstg what do you think?

**Comment by eernstg** [comment] 2023-02-08 10:29
I think the complex response to this code could be caused by the fact that it is a syntax error.

Presumably, the parser detects that `@Meta() static final ...` cannot possibly be a `<classMemberDefinition>`. The parser might then perform some recovery on the AST that it is building, and subsequent diagnostics would be built on an analysis of that AST.

@scheglov, it seems likely that the recovery strategy in this case causes too much reconstruction of things that just aren't there. Do you think there's a need to reconsider the code that does this? Or do you have a completely different explanation for what's going on here?

@jensjoha, I know you have been working on the parser, and you probably don't do that any more, but perhaps you have an opinion anyway? ;-)

**Comment by eernstg** [comment] 2023-02-09 09:07
Thanks, @scheglov!

@sgrekhov, here's one possible way to proceed: We close this issue, await future (possible) test failures on co19/LanguageFeatures/Patterns/variable_declaration_A06_t02 because the diagnostics have changed, and then we just update the test expectations accordingly. If we do that then there won't be an issue on this topic, it will just pop up when it pops up (and then hopefully we can remember what it's all about ;-).

Would that work for you?

**Comment by sgrekhov** [comment] 2023-02-09 14:17
Yes, it works for me. Closing this issue

**Closed** 2023-02-09 14:17 UTC
Labels: question
