### ISSUE TITLE
LanguageFeatures/Records/record_type_annotations_A06_t02, LanguageFeatures/Records/record_type_annotations_A07_t02

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/co19#1494] opened 2022-10-06 19:19 UTC
`d as (int _i, {int n})` throws an error as `d` has a type `(int, double)`:

https://github.com/dart-lang/co19/blob/83feddb44881181ad8f2487080dafe0909517b09/LanguageFeatures/Records/record_type_annotations_A06_t02.dart#L46-L50

Similar problem in record_type_annotations_A07_t02:

https://github.com/dart-lang/co19/blob/83feddb44881181ad8f2487080dafe0909517b09/LanguageFeatures/Records/record_type_annotations_A07_t02.dart#L55-L64

**Comment by sgrekhov** [comment] 2022-10-07 06:09
This is a duplicate of https://github.com/dart-lang/co19/issues/1491

**Closed by sgrekhov** 2022-10-07 06:09 UTC
