### ISSUE TITLE
Failures on [co19] Roll co19 to e8c8b7edab7df1a73c0215da7d458acd0f6c1ef3

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#938] opened 2020-09-17 11:32 UTC
There are new test failures on [[co19] Roll co19 to e8c8b7edab7df1a73c0215da7d458acd0f6c1ef3](https://dart-review.googlesource.com/c/sdk/+/163064).

The tests
```
co19/LanguageFeatures/Set-literals/type_inference_A20_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Set-literals/type_inference_A22_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Set-literals/type_inference_A22_t02 RuntimeError (expected Pass)
co19/LanguageFeatures/Set-literals/type_inference_A24_t01 RuntimeError (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-strong-linux-x64-chrome
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartkp-strong-linux-release-simarm64
dartkp-strong-linux-release-x64
```

**Comment by eernstg** [comment] 2020-09-17 12:17
These failures occur because the changed spec (https://github.com/dart-lang/language/pull/1195) has not yet been landed, and hence the implementation issues have not been created and implementation hasn't occurred. Cf. https://github.com/dart-lang/co19/issues/937.

**Comment by sgrekhov** [comment] 2020-09-18 07:59
These failures caused by missing implementation of spec change, not by test itself. So I'm closing this issue

**Closed by sgrekhov** 2020-09-18 07:59 UTC
