### ISSUE TITLE
Failures on [co19] Roll co19 to 4fa20bd5aa56f2d2f45c94e4e2c90d39fd8575fe

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#1285] opened 2022-02-02 10:04 UTC
There are new test failures on [[co19] Roll co19 to 4fa20bd5aa56f2d2f45c94e4e2c90d39fd8575fe](https://dart-review.googlesource.com/c/sdk/+/231200).

The tests
```
co19/LanguageFeatures/Enhanced-Enum/semantics_A06_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A06_t07 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t02 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t04 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t05 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t06 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t08 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t09 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t10 CompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t11 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t02 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t04 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t05 RuntimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A11_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A11_t02 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A11_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A12_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A13_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A14_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Enhanced-Enum/semantics_A15_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/FinalizationRegistry/expando_key_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/FinalizationRegistry/expando_key_t02 RuntimeError (expected Pass)
co19/LanguageFeatures/FinalizationRegistry/expando_key_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/FinalizationRegistry/expando_key_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/FinalizationRegistry/expando_key_t04 CompileTimeError (expected Pass)
co19/LanguageFeatures/FinalizationRegistry/expando_key_t04 RuntimeError (expected Pass)
    and 3 more tests
```
are failing on configurations
```
analyzer-asserts-strong-linux
analyzer-asserts-weak-linux
cfe-strong-linux
cfe-weak-linux
dart2js-hostasserts-strong-linux-x64-chrome
dart2js-hostasserts-weak-linux-x64-chrome
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartk-strong-win-release-x64
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
dartk-weak-asserts-win-release-x64
dartkp-strong-linux-release-x64
dartkp-weak-asserts-linux-release-x64
```

**Comment by eernstg** [comment] 2022-02-02 17:31
I took a look at the failures:

- `LanguageFeatures/Enhanced-Enum/semantics_A06_t03` CompileTimeError (expected Pass):
  Test issue: uses undefined names `i`, `s`, `E2`.
- `LanguageFeatures/Enhanced-Enum/semantics_A06_t07` MissingCompileTimeError (expected Pass):
  The analyzer does not yet implement these checks.
  `cfe-{strong,weak}-linux` reports errors in a different location. It seems reasonable
  to ask the CFE folks to consider reporting the errors at the
  locations expected by this test (they are currently reported on the
  enum as a whole, and that's not so informative).
- `LanguageFeatures/Enhanced-Enum/semantics_A09_t01` MissingCompileTimeError (expected Pass):
  Test issue: The analyzer complains in line 31 that
  `CONST_CONSTRUCTOR_WITH_FIELD_INITIALIZED_BY_NON_CONST`,
  which is not wrong. This will be a compile-time error because it
  declares a member named `values`, so the initializing expression
  should not introduce an error of its own.
- `LanguageFeatures/Enhanced-Enum/semantics_A09_t02` MissingCompileTimeError (expected Pass):
  Test issue: Line 36, `[]` should be `const []`, similar to previous test.
  Analyzer issue: Doesn't report the conflict between instance members
  and names of enum values.
  `cfe-{strong,weak}-linux` again reports the error on the enum as a
  whole, and again it makes sense to ask the CFE folks to consider
  reporting it as expected in the test.
- `LanguageFeatures/Enhanced-Enum/semantics_A09_t03` MissingCompileTimeError (expected Pass):
  Test issue: The member declarations named `e1` and `e2` should have
  an initializing expression, and it should be constant (or it could
  be done in a constructor initializer list), because it isn't the
  point of this test to detect that those declarations are wrong per se.
  Analyzer issue: Same as _t02.
  `cfe-{strong,weak}-linux`: Also same as _t02.
- `LanguageFeatures/Enhanced-Enum/semantics_A09_t04` MissingCompileTimeError (expected Pass):
  Analyzer issue: Same as _t02.
  `cfe-{strong,weak}-linux` issue: The CFE does not detect the conflicts.
- `LanguageFeatures/Enhanced-Enum/semantics_A09_t05` MissingCompileTimeError (expected Pass):
  Test issue: The description should mention that line 47 expects an
  error because the parameter type is `int` and `E3` is not a subtype
  of `int`, if the setter gets parameter type `E3` there should not be
  an error (that case should probably be added, if it isn't already elsewhere).
  Analyzer issue: The errors are not reported.
  `cfe-{strong,weak}-linux`: Again, the correct errors are reported,
  but the location could be reconsidered (ideally, the user-written
  `e1` and `e2` should probably be blamed).
- `LanguageFeatures/Enhanced-Enum/semantics_A09_t06` MissingCompileTimeError (expected Pass):
  Test issue: Line 24 should not end in a semicolon.
  Analyzer issue: The conflicts in line 36, 47 are not detected.
  `cfe-{strong,weak}-linux` issue: The CFE does not detect the conflicts.
- `LanguageFeatures/Enhanced-Enum/semantics_A09_t08` MissingCompileTimeError (expected Pass):
  Test issue: Mixin `M2` cannot meaningfully be `on Enum`, because it
  has an instance variable, so applications of it won't get a constant
  constructor. Could delete `M2`, but could also test for detection of
  that error.
  Analyzer issue: The conflicts are not reported.
- `LanguageFeatures/Enhanced-Enum/semantics_A09_t09` MissingCompileTimeError (expected Pass):
  Test issue: `cfe-{strong,weak}-linux` has a test failure, but it seems
  appropriate: It reports that 'The non-abstract class 'E4' is missing
  implementations', and that is true, so the test should expect that
  error (the CFE error location is the whole enum, and that does make
  sense, so in this case it's probably not useful to raise that as an issue).
- `LanguageFeatures/Enhanced-Enum/semantics_A09_t10` CompileTimeError (expected Pass):
  Test issue: `E3` line 52 should probably be `E2`.
  CFE issue, also seen with `dart2js`, `dartk` and other users of the
  CFE: The type of `E2.e1` is considered to be `E2<dynamic>`, but it
  should be `E2<int>`, so there should not be a setter/getter
  signature error.
- `LanguageFeatures/Enhanced-Enum/semantics_A09_t11` MissingCompileTimeError (expected Pass):
  Test issue: `E3` line 54 should probably be `E2`.
  Analyzer issue: Getter/setter signature mismatch error not detected.
  `cfe-{strong,weak}-linux` issue: Getter/setter signature mismatch
  error reported at a different line (as usual, this may be ok or not,
  to be discussed with the CFE team). `E2.e1` is considered to have type
  `E2<dynamic>`, should be `E2<int>` + same for `e2`, `e3`.
- `LanguageFeatures/Enhanced-Enum/semantics_A10_t01` MissingCompileTimeError (expected Pass):
  Analyzer issue: `index` override error not detected, error because
  `index` can't be overridden at all not reported. `toString` override
  error not reported.
- `LanguageFeatures/Enhanced-Enum/semantics_A10_t02` MissingCompileTimeError (expected Pass):
  Analyzer issue: `index` and `toString` static/instance conflict not
  reported. No error for declaring the static `index` at all reported.
- `LanguageFeatures/Enhanced-Enum/semantics_A10_t03` MissingCompileTimeError (expected Pass):
  CFE issues: The error message should probably not mention
  `_Enum`. The override errors for `index` and `toString` are reported
  correctly, but on `E1` where `M1` is applied, and they could be
  reported in `M1` (there is no way `M1` could be successfully applied
  to any superclass). The errors on line 48 are not informative.
- `LanguageFeatures/Enhanced-Enum/semantics_A10_t04` MissingCompileTimeError (expected Pass):
  Analyzer issue: The override error for operator `==` is not reported.
- `LanguageFeatures/Enhanced-Enum/semantics_A10_t05 RuntimeError (expected Pass):
  `dartdevk-{strong,weak}-linux-release-chrome` issue: Wrong semantics
  in evaluation of operator `==` of `E1` (probably others, too, but
  the test throws and terminates at that point).
- `LanguageFeatures/Enhanced-Enum/semantics_A11_t01` MissingCompileTimeError (expected Pass):
  Test issue: I don't see why there should be an error at line 41.
  Analyzer issue: Errors line 24, 28, 46, that a member of the
  interface of the enclosing enum is not implemented, are not reported.
- `LanguageFeatures/Enhanced-Enum/semantics_A11_t02` MissingCompileTimeError (expected Pass):
  Analyzer issue: Missing implementation of `I.toString` not reported.
- `LanguageFeatures/Enhanced-Enum/semantics_A11_t03` MissingCompileTimeError (expected Pass):
  Analyzer issue: Missing implementation of `I.foo` not reported.
- `LanguageFeatures/Enhanced-Enum/semantics_A12_t01` CompileTimeError (expected Pass):
  Test issue: The constructor must have the name `E`, not `E2`. `E1`
  in `main` is undefined (and `E2.e1` should be `E1.e2`?).
  Also note that the description does not match the test:
  Instantiation to bounds on `E` yields `E<List<dynamic>>`, no problem.
- `LanguageFeatures/Enhanced-Enum/semantics_A13_t01` MissingCompileTimeError (expected Pass):
  Possible test issue: This looks like a duplicate of an earlier test?
  Analyzer issue: Missing implementation of `toString`, `foo` not reported.
- `LanguageFeatures/Enhanced-Enum/semantics_A14_t01` MissingCompileTimeError (expected Pass):
  Analyzer issue: It is not detected that arguments to enum values are
  not constant expressions.
  CFE issue: It is not detected for `E1` that arguments to enum values
  are not constant expressions. It is reported for the enum as a whole
  that some constant evaluation fails, so that should probably be
  reported in a more informative location.
- `LanguageFeatures/Enhanced-Enum/semantics_A15_t01` MissingCompileTimeError (expected Pass):
  Analyzer issue: It is not reported that it is an error to declare a static
  `index` at all (it conflicts with an instance getter in a
  superinterface). Same for a static `toString`.

**Comment by sgrekhov** [comment] 2022-02-03 09:14
@eernstg thank you for the detailed explanation of all failures! It helped me much! I fixed tests issues and created analyzer/CFE ones.

**Comment by sgrekhov** [comment] 2022-02-03 09:15
analyzer... |  
-- | --
new test -> MissingCompileTimeError (expected Pass) |  
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t01 | Fixed, https://github.com/dart-lang/sdk/issues/48289
co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t01 | https://github.com/dart-lang/sdk/issues/48290
co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t02 | https://github.com/dart-lang/sdk/issues/48290
co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t04 | https://github.com/dart-lang/sdk/issues/48290
co19/LanguageFeatures/Enhanced-Enum/semantics_A11_t02 | https://github.com/dart-lang/sdk/issues/48291
co19/LanguageFeatures/Enhanced-Enum/semantics_A11_t03 | https://github.com/dart-lang/sdk/issues/48291
co19/LanguageFeatures/Enhanced-Enum/semantics_A15_t01 | https://github.com/dart-lang/sdk/issues/48290
analyzer...cfe... |  
new test -> MissingCompileTimeError (expected Pass) |  
co19/LanguageFeatures/Enhanced-Enum/semantics_A06_t07 | https://github.com/dart-lang/sdk/issues/48292,https://github.com/dart-lang/sdk/issues/48293
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t02 | Fixed,https://github.com/dart-lang/sdk/issues/48290,https://github.com/dart-lang/sdk/issues/48293
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t03 | https://github.com/dart-lang/sdk/issues/48290,https://github.com/dart-lang/sdk/issues/48293
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t04 | https://github.com/dart-lang/sdk/issues/48290,https://github.com/dart-lang/sdk/issues/48294
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t05 | https://github.com/dart-lang/sdk/issues/48293,https://github.com/dart-lang/sdk/issues/48295
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t06 | https://github.com/dart-lang/sdk/issues/48294,https://github.com/dart-lang/sdk/issues/48295
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t08 | https://github.com/dart-lang/sdk/issues/48295
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t09 | Fixed,https://github.com/dart-lang/sdk/issues/48295
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t11 | Fixed, https://github.com/dart-lang/sdk/issues/48293,https://github.com/dart-lang/sdk/issues/48296
co19/LanguageFeatures/Enhanced-Enum/semantics_A11_t01 | Fixed,https://github.com/dart-lang/sdk/issues/48291
co19/LanguageFeatures/Enhanced-Enum/semantics_A13_t01 | Deleted
co19/LanguageFeatures/Enhanced-Enum/semantics_A14_t01 | https://github.com/dart-lang/sdk/issues/48292,https://github.com/dart-lang/sdk/issues/48293
analyzer...cfe...dart2js...dartdevk...dartk...dartkp... |  
new test -> CompileTimeError (expected Pass) |  
co19/LanguageFeatures/Enhanced-Enum/semantics_A06_t03 | Fixed
co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t10 | Fixed, https://github.com/dart-lang/sdk/issues/48297
co19/LanguageFeatures/Enhanced-Enum/semantics_A12_t01 | Fixed
cfe... |  
new test -> MissingCompileTimeError (expected Pass) |  
co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t03 | https://github.com/dart-lang/sdk/issues/48298
dart2js...dartdevk.. |  
new test -> CompileTimeError (expected Pass) |  
co19/LanguageFeatures/FinalizationRegistry/expando_key_t03 | https://github.com/dart-lang/sdk/issues/48264
co19/LanguageFeatures/FinalizationRegistry/expando_key_t04 | https://github.com/dart-lang/sdk/issues/48264
co19/LanguageFeatures/FinalizationRegistry/expando_key_t05 | https://github.com/dart-lang/sdk/issues/48264
dartdevk... |  
new test -> RuntimeError (expected Pass) |  
co19/LanguageFeatures/Enhanced-Enum/semantics_A10_t05 | https://github.com/dart-lang/sdk/issues/48299
dartk...dartkp... |  
new test -> RuntimeError (expected Pass) |  
co19/LanguageFeatures/FinalizationRegistry/expando_key_t01 | https://github.com/dart-lang/sdk/issues/48264
co19/LanguageFeatures/FinalizationRegistry/expando_key_t02 | https://github.com/dart-lang/sdk/issues/48264
co19/LanguageFeatures/FinalizationRegistry/expando_key_t03 | https://github.com/dart-lang/sdk/issues/48264
co19/LanguageFeatures/FinalizationRegistry/expando_key_t04 | https://github.com/dart-lang/sdk/issues/48264
co19/LanguageFeatures/FinalizationRegistry/expando_key_t05 | https://github.com/dart-lang/sdk/issues/48264
dartk... |  
dartkp-weak-asserts-linux-release-x64new test -> RuntimeError (expected Pass) |  
co19/LanguageFeatures/FinalizationRegistry/expando_key_t06 | https://github.com/dart-lang/sdk/issues/48264

**Closed by sgrekhov** 2022-02-03 09:15 UTC
