### ISSUE TITLE
Add constant-update-2018 flag to collections tests

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/co19#337] opened 2019-03-27 08:32 UTC
All tests in `LanguageFeatures/Control-flow-collections` and `LanguageFeatures/Spread-collections` that contain `const` collections need to enable the `constant-update-2018` experiment to function properly.

This can be done similarly to https://dart-review.googlesource.com/c/sdk/+/97939

**Comment by sgrekhov** [comment] 2019-03-27 08:38
Duplicate of #332. Already fixed. Closed

**Closed by sgrekhov** 2019-03-27 08:38 UTC
Labels: P1

**Comment by askeksa-google** [comment] 2019-03-27 08:41
Ah, somehow overlooked that issue when I looked for it. Thanks!
