### ISSUE TITLE
Failures on newly migrated tests

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#688] opened 2020-05-26 11:42 UTC
There are new test failures on [[infra] Run all migrated co19 tests on nnbd configurations](https://dart-review.googlesource.com/c/sdk/+/149002).

The tests
```
co19/LanguageFeatures/Subtyping/dynamic/generated/left_legacy_arguments_binding_A02_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_legacy_arguments_binding_A02_t02 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_legacy_arguments_binding_A02_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_legacy_class_member_A02_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_legacy_class_member_A02_t02 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_legacy_class_member_A02_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_legacy_global_variable_A02_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_legacy_local_variable_A02_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_legacy_return_value_A02_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_nullable_fail_arguments_binding_fail_A01_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_nullable_fail_arguments_binding_fail_A01_t02 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_nullable_fail_arguments_binding_fail_A01_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_nullable_fail_class_member_fail_A01_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_nullable_fail_class_member_fail_A01_t02 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_nullable_fail_class_member_fail_A01_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_nullable_fail_global_variable_fail_A01_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_nullable_fail_local_variable_fail_A01_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_nullable_fail_return_value_fail_A01_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/left_top_global_variable_A01_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_arguments_binding_A01_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_arguments_binding_A01_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_arguments_binding_A01_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_arguments_binding_A03_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_arguments_binding_A03_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_arguments_binding_A03_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_class_member_A01_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_class_member_A01_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_class_member_A01_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_class_member_A03_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Subtyping/dynamic/generated/right_FutureOr_class_member_A03_t02 CompileTimeError (expected Pass)
    and 609 more tests
```
are failing on configurations
```
analyzer-asserts-strong-linux
analyzer-asserts-weak-linux
cfe-strong-linux
cfe-weak-linux
dart2js-hostasserts-strong-linux-x64-chrome
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```

**Comment by crelier** [comment] 2020-05-27 16:30
@athomas Thanks!
I was going to continue today with this triage (only for runtime errors on the VM). So I am glad you asked @sgrekhov to do an initial pass. I was going to suggest that the co19 folks (and maybe the language team for unclear border cases) always have a look first before rolling new or migrated co19 tests. Great!
Please, let us know when we can resume looking at actual issues. Thanks

**Comment by sgrekhov** [comment] 2020-05-29 06:38
After the fix, locally I have the following. 
Configurations
```
analyzer-asserts-strong-linux
analyzer-asserts-weak-linux
cfe-strong-linux
cfe-weak-linux
```
are ok. Each of them has < 10 failures caused by not supported type aliases in analyzer and https://github.com/dart-lang/sdk/issues/42089 issue

Configurations
```
dartk-strong-linux-release-x64
dartk-strong-debug-release-x64
```
have no any issues at all.

I'm unable to test configurations that use browser locally. It simply hangs out
```
dart2js-hostasserts-strong-linux-x64-chrome
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
```
Configurations
```
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```
have 27 failures each. Partially it's https://github.com/dart-lang/sdk/issues/42089, partially it is an issue of dartk weak mode. I filled https://github.com/dart-lang/sdk/issues/42109

@athomas I believe this issue can be closed and the new roll is performed.

**Comment by sgrekhov** [comment] 2020-06-01 08:01
Weak mode failures fixed. Closing this

**Closed by sgrekhov** 2020-06-01 08:01 UTC
Labels: P1
