### ISSUE TITLE
Overriding legacy in opt-in and required named formal parameters

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#520] opened 2020-01-31 19:33 UTC
With [this CL](https://dart-review.googlesource.com/c/sdk/+/134043) analyzer reports override errors for tests:
```
co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t01
co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t03
co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t05
co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t07
co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t09
co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t11
co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t13
co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t15
co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t18
co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t20
```

And example of output:
```
DART_CONFIGURATION=ReleaseX64NNBD out/ReleaseX64NNBD/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=machine --no-hints /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t01.dart

exit code:
1

stderr:
ERROR|COMPILE_TIME_ERROR|INVALID_OVERRIDE|/b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t01.dart|25|8|15|'A.test_nondefault' ('void Function({required int? i})') isn't a valid override of 'LEGACY_REQUIRED_ARGS.test_nondefault' ('void Function({int* i})*').
ERROR|COMPILE_TIME_ERROR|INVALID_OVERRIDE|/b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t01.dart|24|8|12|'A.test_default' ('void Function({required int? i})') isn't a valid override of 'LEGACY_REQUIRED_ARGS.test_default' ('void Function({int* i})*').

--- Re-run this test:
python tools/test.py -n analyzer-asserts-strong-linux co19/LanguageFeatures/nnbd/override_checking_A02_REQ_ARGS_t01
```

@eernstg  I think these are valid errors, because [the spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md) says: `If a class C in an opted-in library overrides a member, it is an error if its signature is not a subtype of the types of all overriden members from all super-interfaces (whether legacy or opted-in).` And according to the [subtyping rules](https://github.com/dart-lang/language/blob/master/resources/type-system/subtyping.md) `required` parameters in the subtype should have corresponding `required` parameters in the supertype.

**Comment by eernstg** [comment] 2020-01-31 20:29
https://github.com/dart-lang/language/pull/789 changed a number of elements in the nnbd feature specification such that it uses what we have called the consolidated model: Each class has an interface which is computed based on its declarations and the direct super-interfaces, and a class defined in an opted-out library has an interfaces whose member signatures are all fully legacy types.

So when we consider the overriding relationship for any given member `m` it is always between the member signature of `m` in the current class (there is one, because we're focusing on overrides) and the member signature for `m` from each of the direct superinterfaces of the class that have an `m`. This implies that we need to adjust a few more things, for instance the example at the end of ['Classes defined in opted-in libraries'](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#classes-defined-in-opted-in-libraries), where override checking is now performed against the signature `int* foo(int*)` from the interface of `B`.

Similarly, we'll need to adjust the requirement that the function types derived from the member signatures are such that the overrider is a subtype of the overridee: That rule needs to apply the same kind of erasure of parameter types for parameters that are covariant-by-declaration as we do in the language specification. (There needs to be a separate "covariant parameter type check" for the appropriateness of the actual type annotation of such parameters, relative to each corresponding parameter in any superinterface, not just the direct ones; but I believe that this rule would just work as stated in the language specification).

The question then arises: How should we treat `required` named parameters? In a pure nnbd type comparison there is no question, a supertype must require everything that the subtype requires, for soundness.

But when we consider the relationship between an nnbd type and a legacy type, we usually allow the legacy type to claim whatever it needs in terms of nnbd properties: `int? Function(int) <: int* Function(int*)` because the first `*` can be turned into a `?` and the second `*` can be turned into nothing.

So do we want to allow a named parameter with type `T*` to be considered as `required T` and `required T?` as well as `T` and `T?`?

The motivation would be that there is no other way the legacy code can be compatible with down-stream opted-in code that needs to use `required` named parameters: As long as the overridden parameter is legacy, it can't be required, so the overrider also cannot be `required`.

Comparing the treatment of `?` and `required` it seems inconsistent that the legacy member signature can admit all usages of `?` in overriders, but it cannot admit any use of `required` at all.

**Comment by eernstg** [comment] 2020-01-31 20:51
Cf. https://github.com/dart-lang/language/issues/812.

**Comment by iarkh** [comment] 2021-04-08 10:36
Now all the tests pass both with dart and analyzer, so I am closing a bug.
Please note that related SDK Issue [#41527](https://github.com/dart-lang/sdk/issues/41527) is also not reproducible.

**Closed by iarkh** 2021-04-08 10:36 UTC
