### ISSUE TITLE
LibTest/io/file_utils.dart needs hardening

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/co19#672] opened 2020-05-20 09:23 UTC
We're currently seeing CI failures for `co19_2/LibTest/io/FileSystemCreateEvent/path_A01_t01` on MacOS:
```
Unhandled exception:
Expect.equals(expected: </b/s/w/itw42ZU8/path_A01_t01_ciXLWP/path_A01_t01_lLmRBk/wOspsV>, actual: </b/s/w/itw42ZU8/path_A01_t01_ciXLWP/path_A01_t01_lLmRBk>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.equals (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:30:5)
#2      _main.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/path_A01_t01.dart:32:16)
#3      testFileSystemEvent (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:53:7)
<asynchronous suspension>
#4      _main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/path_A01_t01.dart:28:9)
#5      inSandbox (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:24:22)
#6      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/path_A01_t01.dart:20:9)
[...]
```

After a dive into the test code I _suspect_ this might have been triggered by an unrelated change, which likely exposed some non-determinism in the FS watcher code.

The failing test itself tests:
```
  Directory dir = getTempDirectorySync(parent: sandbox);
...
  await testFileSystemEvent<FileSystemCreateEvent>(dir,
      createEvent: () {
        path = dir.createTempSync().path;
      }, test: (FileSystemEvent event) {
        Expect.equals(path, event.path);
      });
```
Which fails by receiving _some_ event that contains the path to the temp directory instead of the temp file.

Playing around with the file_utils code, I see that it is made to call the `test` function on the first event that happens in `dir`. But since it is subscribed to all event types, this can be any number of events.
The [watch](https://api.dart.dev/stable/2.8.2/dart-io/FileSystemEntity/watch.html) method specifically mentions being platform specific, and it doesn't mention any guarantees for e.g. order or timeliness of events.

This leads me to believe that `testFileSystemEvent` and/or the test code likely needs to be made more robust and make less assumptions about what events happen when - assuming the file create event is the first and only event likely holds in most cases but also likely not in all.

I see a couple of different options including:
- Make `testFileSystemEvent` take and pass `events` to `watch(events:events)` which would allow the test to subscribe to only a subset of events.
Though it is also likely this wouldn't be granular enough on its own as Create events appear to be both directories and files.
- Make the `test` function receive all events and make the test fail if it didn't receive the expected event before the timeout.

(Please note that I have not been able to verify these speculations myself since I don't have access to a MacOS machine at the moment)

**Comment by zichangg** [comment] 2020-05-21 18:19
Another relative failure today:
https://dart-ci.appspot.com/log/vm-kernel-mac-release-x64/dartk-mac-release-x64/8810/co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t02

**Comment by sgrekhov** [comment] 2020-05-22 04:20
I added to `testFileSystemEvent` additional parameter 'bool ignoreRootEvents = true'. So, now it ignores events coming from the root temp directory itself. I'm unable to test if it fix the issue on Mac OS, I only checked that test are still working on other OSs. But if @cskau-g's guesses are true then it must to fix the issue. So I'm closing it now. If the issue is not fixed, please, feel free to reopen this issue

**Closed by sgrekhov** 2020-05-22 04:20 UTC
