### ISSUE TITLE
A name clash between a named and a positional field isn't marked as a compile-time error

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1536] opened 2022-11-07 15:00 UTC
This line in the test should be treated as a compile-time error because the record type has a positional field and the named field of that type has name `$0`.

https://github.com/dart-lang/co19/blob/4b2135b3330978725041348a0573e556c2efcea4/LanguageFeatures/Records/record_type_annotations_A07_t02.dart#L53

**Comment by sgrekhov** [comment] 2022-11-07 18:19
This is a duplicate of #1529. https://github.com/dart-lang/co19/pull/1532 fixes it. Please review

**Closed by sgrekhov** 2022-11-07 18:19 UTC
