### ISSUE TITLE
co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t06 flaked on Mac

### ISSUE THREAD

**Issue by mraleph** [dart-lang/co19#196] opened 2018-11-26 10:34 UTC
It is currently unclear if this is a test issue or a VM issue.

I am going to add printing to verify.

```
FAILED: dartk-vm product_x64 co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t06
Expected: Timeout Pass
Actual: RuntimeError

--- Command "vm" (took 833ms):
DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t06.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.isFalse(true) fails.
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.isFalse (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:48:5)
#2      _main.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t06.dart:33:16)
#3      testFileSystemEvent (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:53:7)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#9      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:737:16)
#10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m product -n dartk-mac-product-x64 co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t06
```

**Comment by sgrekhov** [comment] 2018-12-06 10:56
Duplicate of #186. See https://github.com/dart-lang/co19/issues/186#issuecomment-443188150

**Closed by sgrekhov** 2018-12-06 10:56 UTC
