### ISSUE TITLE
Tests wrongly expecting type arguments to be modified by NNBD_TOP_MERGE

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#631] opened 2020-04-30 22:18 UTC
The following tests wrongly expect class type arguments to be modified by NNBD_TOP_MERGE:

LanguageFeatures/nnbd/overriding/override_checking_A06_t012
LanguageFeatures/nnbd/overriding/override_checking_A06_t026
LanguageFeatures/nnbd/overriding/override_checking_A06_t029
LanguageFeatures/nnbd/overriding/override_checking_A06_t043
LanguageFeatures/nnbd/overriding/override_checking_A06_t047
LanguageFeatures/nnbd/overriding/override_checking_A06_t052
LanguageFeatures/nnbd/overriding/override_checking_A06_t054
LanguageFeatures/nnbd/overriding/override_checking_A06_t071
LanguageFeatures/nnbd/overriding/override_checking_A06_t072
LanguageFeatures/nnbd/overriding/override_checking_A06_t085
LanguageFeatures/nnbd/overriding/override_checking_A06_t100
LanguageFeatures/nnbd/overriding/override_checking_A06_t115
LanguageFeatures/nnbd/overriding/override_checking_A06_t121
LanguageFeatures/nnbd/overriding/override_checking_A06_t122
LanguageFeatures/nnbd/overriding/override_checking_A06_t124
LanguageFeatures/nnbd/overriding/override_checking_A06_t130
LanguageFeatures/nnbd/overriding/override_checking_A06_t147
LanguageFeatures/nnbd/overriding/override_checking_A06_t148
LanguageFeatures/nnbd/overriding/override_checking_A06_t154
LanguageFeatures/nnbd/overriding/override_checking_A06_t156
LanguageFeatures/nnbd/overriding/override_checking_A06_t159

See also https://github.com/dart-lang/co19/issues/623

**Comment by iarkh** [comment] 2020-05-01 05:12
It's a duplicate of the Issues #619, #623 which already were fixed yesterday.

**Closed by iarkh** 2020-05-01 05:12 UTC
